name: Filter PR Contents

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  filter-directories:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Reset protected directories changes
        run: |
          git fetch origin main:main

          git checkout main -- data/
          git checkout main -- public/

          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "🤖 Automatically exclude data/ and public/ directory changes"
            git push
          else
            echo "No changes in protected directories, nothing to do."
          fi
